language: python
sudo: required
dist: xenial

env:
  global:
    - DIST=dist/app

python:
  - "3.7"
install:
  - pip install -r requirements.txt
script:
  - pyinstaller app.py
after_success:
  - tar -zcf ${TRAVIS_BUILD_DIR}-${TRAVIS_BUILD_NUMBER}.tar.gz ${DIST}